name: Build App

on:
  push:
    branches:
      - main
  workflow_dispatch:
   inputs:
    environment:
      description: "Environment"
      required: false
      default: "dev"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: echo "OK"
