name: Build App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Compilar aplicación
        run: |
          python -m py_compile app.py
          mkdir -p build
          cp app.py build/

      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: python-build
          path: build/
